In [1]:
# importing the libraries
import numpy as np
import pandas as pd

### 2.6 Pandas -  Series and DataFrames

**Pandas Series**
* Pandas Series is a one-dimensional labeled array/list capable of holding data of any type (integer, string, float, python objects, etc.).
* The labels are collectively called index.
* Pandas Series can be thought as a single column of an excel spreadsheet and each entry in a series corresponds to an individual row in the spreadsheet.

In [ ]:
# creating a list of price of different medicines
med_price_list = [55,25,75,40,90]

# converting the med_price_list to an array
med_price_arr = np.array(med_price_list)

# converting the list and array into a Pandas Series object
series_list = pd.Series(med_price_list)
series_arr = pd.Series(med_price_arr)

# printing the converted series object
print(series_list)
print(series_arr)

0    55
1    25
2    75
3    40
4    90
dtype: int64
0    55
1    25
2    75
3    40
4    90
dtype: int64

* We can see that the list and array have been converted to a Pandas Series object.
* We also see that the series has automatically got index labels. Let's see how these can be modified.

In [ ]:
# changing the index of a series
med_price_list_labeled = pd.Series(med_price_list, index = ['Omeprazole','Azithromycin','Metformin','Ibuprofen','Cetirizine'])
print(med_price_list_labeled)

Omeprazole      55
Azithromycin    25
Metformin       75
Ibuprofen       40
Cetirizine      90
dtype: int64

**Performing mathematical operations on Pandas Series**

* The price of each medicine was increased by $2.5. Let's add this to the existing price.

In [ ]:
# adding 2.5 to existing prices
med_price_list_labeled_updated = med_price_list_labeled + 2.5
med_price_list_labeled_updated

Omeprazole      57.5
Azithromycin    27.5
Metformin       77.5
Ibuprofen       42.5
Cetirizine      92.5
dtype: float64

* A new price list was released by vendors for each medicine. Let's find the difference between new price and the old price

In [ ]:
new_price_list = [77, 45.5, 100, 50, 80]
new_price_list_labeled = pd.Series(new_price_list, index = ['Omeprazole','Azithromycin','Metformin','Ibuprofen','Cetirizine'])
print(new_price_list_labeled)

Omeprazole       77.0
Azithromycin     45.5
Metformin       100.0
Ibuprofen        50.0
Cetirizine       80.0
dtype: float64

In [ ]:
print('Difference between new price and old price - ')
print(new_price_list_labeled - med_price_list_labeled_updated)

Difference between new price and old price -
Omeprazole      19.5
Azithromycin    18.0
Metformin       22.5
Ibuprofen        7.5
Cetirizine     -12.5
dtype: float64

**Pandas DataFrame**

Pandas DataFrame is a two-dimensional tabular data structure with labeled axes (rows and columns).

**Creating a Pandas DataFrame using a list**

In [ ]:
student = ['Mary', 'Peter', 'Susan', 'Toby', 'Vishal']
df1 = pd.DataFrame(student,columns=['Student'])
df1

  Student
0    Mary
1   Peter
2   Susan
3    Toby
4  Vishal

**Creating a Pandas DataFrame using a dictionary**

In [ ]:
# defining another list
grades = ['B-','A+','A-', 'B+', 'C']

# creating the dataframe using a dictionary
df2 = pd.DataFrame({'Student':student,'Grade':grades})
df2

  Student Grade
0    Mary    B-
1   Peter    A+
2   Susan    A-
3    Toby    B+
4  Vishal     C

**Creating a Pandas DataFrame using Series**

The data for total energy consumption for the U.S. was collected from 2012 - 2018. Let's see how this data can be presented in form of data frame.

In [ ]:
year = pd.Series([2012,2013,2014,2015,2016,2017,2018])
energy_consumption = pd.Series([2152,2196,2217,2194,2172,2180,2258])

df3 = pd.DataFrame({'Year':year,'Energy_Consumption(Mtoe)':energy_consumption})
df3

   Year  Energy_Consumption(Mtoe)
0  2012                      2152
1  2013                      2196
2  2014                      2217
3  2015                      2194
4  2016                      2172
5  2017                      2180
6  2018                      2258

**Creating a Pandas DataFrame using random values**

For encryption purposes a web browser company wants to generate random values which have mean equal to 0 and variance equal to 1. They want 5 randomly generated numbers in 2 different trials.

In [ ]:
# we can create a new dataframe using random values
df4 = pd.DataFrame(np.random.randn(5,2),columns = ['Trial 1', 'Trial 2'])
df4

    Trial 1   Trial 2
0  0.740967  0.935937
1  1.519597  0.013860
2  0.259383 -0.824822
3 -0.744735 -0.039417
4  0.156586 -0.348059

### 2.7 Pandas - Accessing and Modifying

**Accessing Series**

The revenue (in billion dollars) of different telecommunication operators in U.S. was collected for the year of 2020. The following lists consist of the names of the telecommunication operators and their respective revenue (in billion dollars).

In [ ]:
operators = ['AT&T', 'Verizon', 'T-Mobile US', 'US Cellular']
revenue = [171.76, 128.29, 68.4, 4.04]

#creating a Series from lists
telecom = pd.Series(revenue, index=operators)
telecom

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

**Accessing Pandas Series using its index**

In [ ]:
# accessing the first element of series
telecom[0]

171.76

In [ ]:
#  accessing firt 3 elements of a series
telecom[:3]

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [ ]:
# accessing the last two elements of a series
telecom[-2:]

T-Mobile US    68.40
US Cellular     4.04
dtype: float64

In [ ]:
# accessing multiple elements of a series
telecom[[0,2,3]]

AT&T           171.76
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

**Accessing Pandas Series using its labeled index**

In [ ]:
# accessing the revenue of AT&T
telecom['AT&T']

171.76

In [ ]:
#  accessing firt 3 revenues of operators in the series
telecom[:'T-Mobile US']

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [ ]:
# accessing multiple values
telecom[['AT&T','US Cellular','Verizon']]

AT&T           171.76
US Cellular      4.04
Verizon        128.29
dtype: float64

**Accessing DataFrames**

The data of the customers visiting 24/7 Stores from different locations was collected. The data includes Customer ID, location of store, gender of the customer,  type of product purchased, quantity of products purchased, total bill amount. Let's create the dataset and see how to access different entries of it.

In [ ]:
# creating the dataframe using dictionary
store_data = pd.DataFrame({'CustomerID': ['CustID00','CustID01','CustID02','CustID03','CustID04']
                           ,'location': ['Chicago', 'Boston', 'Seattle', 'San Francisco', 'Austin']
                           ,'gender': ['M','M','F','M','F']
                           ,'type': ['Electronics','Food&Beverages','Food&Beverages','Medicine','Beauty']
                           ,'quantity':[1,3,4,2,1],'total_bill':[100,75,125,50,80]})
store_data

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [ ]:
# accessing first row of the dataframe
store_data[:1]

  CustomerID location gender         type  quantity  total_bill
0   CustID00  Chicago      M  Electronics         1         100

In [ ]:
# accessing first column of the dataframe
store_data['location']

0          Chicago
1           Boston
2          Seattle
3    San Francisco
4           Austin
Name: location, dtype: object

In [ ]:
# accessing rows with the step size of 2
store_data[::2]

  CustomerID location gender            type  quantity  total_bill
0   CustID00  Chicago      M     Electronics         1         100
2   CustID02  Seattle      F  Food&Beverages         4         125
4   CustID04   Austin      F          Beauty         1          80

In [ ]:
# accessing the rows in reverse
store_data[::-2]

  CustomerID location gender            type  quantity  total_bill
4   CustID04   Austin      F          Beauty         1          80
2   CustID02  Seattle      F  Food&Beverages         4         125
0   CustID00  Chicago      M     Electronics         1         100

**Using loc and iloc method**

**loc method**

* loc is a  method to access rows and columns on pandas objects. When using the loc method on a dataframe, we specify which rows and which columns we want by using the following format:

  * **dataframe.loc[row selection, column selection]**

* DataFrame.loc[] method is a method that takes **only index labels** and returns row or dataframe if the index label exists in the data frame.

In [ ]:
# accessing first index value using loc method (indexing starts from 0 in python)
store_data.loc[1]

CustomerID          CustID01
location              Boston
gender                     M
type          Food&Beverages
quantity                   3
total_bill                75
Name: 1, dtype: object

**Accessing selected rows and columns using loc method**

In [ ]:
# accessing 1st and 4th index values along with location and type columns
store_data.loc[[1,4],['location','type']]

  location            type
1   Boston  Food&Beverages
4   Austin          Beauty

**iloc method**

* The iloc indexer for Pandas Dataframe is used for **integer location-based** indexing/selection by position. When using the loc method on a dataframe, we specify which rows and which columns we want by using the following format:

  * **dataframe.iloc[row selection, column selection]**

In [ ]:
# accessing selected rows and columns using iloc method
store_data.iloc[[1,4],[0,2]]

  CustomerID gender
1   CustID01      M
4   CustID04      F

**Difference between loc and iloc indexing methods**

* loc is label-based, which means that you have to specify rows and columns based on their row and column labels.
* iloc is integer position-based, so you have to specify rows and columns by their integer position values (0-based integer position).

If we use labels instead of index values in .iloc it will throw an error.

In [ ]:
# accessing selected rows and columns using iloc method
store_data.iloc[[1,4],['location','type']]

IndexError: ignored

* As expected, .iloc has given error on using 'labels'.

We can modify entries of a dataframe using loc or iloc too

In [ ]:
print(store_data.loc[4,'type'])
store_data.loc[4,'type'] = 'Electronics'

Beauty

In [ ]:
store_data

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F     Electronics         1          80

In [ ]:
store_data.iloc[4,3] = 'Beauty'
store_data

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

**Condition based indexing**

In [ ]:
store_data['quantity']>1

0    False
1     True
2     True
3     True
4    False
Name: quantity, dtype: bool

* Wherever the condition of greater than 1 is satisfied in quantity column, 'True' is returned. Let's retrieve the original values wherever the condition is satisfied.

In [ ]:
store_data.loc[store_data['quantity']>1]

  CustomerID       location gender            type  quantity  total_bill
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50

* Wherever the condition is satisfied we get the original values, and wherever the condition is not satisfied we do not get those records in the output.

**Column addition and removal from a Pandas DataFrame**

**Adding a new column in a DataFrame**

In [ ]:
store_data

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [ ]:
# adding a new column in data frame store_data which is a rating (out of 5) given by customer based on their shopping experience
store_data['rating'] = [2,5,3,4,4]
store_data

  CustomerID       location gender  ... quantity  total_bill  rating
0   CustID00        Chicago      M  ...        1         100       2
1   CustID01         Boston      M  ...        3          75       5
2   CustID02        Seattle      F  ...        4         125       3
3   CustID03  San Francisco      M  ...        2          50       4
4   CustID04         Austin      F  ...        1          80       4

[5 rows x 7 columns]

**Removing a column from a DataFrame**

* The CustomerID column is a unique identifier of each customer. This unique identifier will not help 24/7 Stores in getting useful insights about their customers. So, they have decided to remove this column from the data frame.

In [ ]:
store_data.drop('CustomerID',axis=1)

        location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1         Boston      M  Food&Beverages         3          75       5
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

* We sucessfully removed the 'CustomerID' from dataframe. But this change is not permanent in the dataframe, let's have a look at the store_data again.

In [ ]:
store_data

  CustomerID       location gender  ... quantity  total_bill  rating
0   CustID00        Chicago      M  ...        1         100       2
1   CustID01         Boston      M  ...        3          75       5
2   CustID02        Seattle      F  ...        4         125       3
3   CustID03  San Francisco      M  ...        2          50       4
4   CustID04         Austin      F  ...        1          80       4

[5 rows x 7 columns]

* We see that store_data still has column 'CustomerID' in it.
* To make permanent changes to a dataframe there are two methods will have to use a parameter `inplace` and set its value to `True`.

In [ ]:
store_data.drop('CustomerID',axis=1,inplace=True)
store_data

        location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1         Boston      M  Food&Beverages         3          75       5
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

* Now the column has been permanently removed from the dataframe.

In [ ]:
# we can also remove multiple columns simultaneously
# it is always a good idea to store the new/updated data frames in new variables to avoid changes to the existing data frame

# creating a copy of the existing data frame
new_store_data = store_data.copy()
store_data

        location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1         Boston      M  Food&Beverages         3          75       5
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

In [ ]:
# dropping location and rating columns simultaneously
new_store_data.drop(['location','rating'],axis=1,inplace=True)
new_store_data

  gender            type  quantity  total_bill
0      M     Electronics         1         100
1      M  Food&Beverages         3          75
2      F  Food&Beverages         4         125
3      M        Medicine         2          50
4      F          Beauty         1          80

In [ ]:
# lets check if store_data was impacted
store_data

        location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1         Boston      M  Food&Beverages         3          75       5
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

* There were no changes to data frame store_data.

* Deep copy stores copies of the object’s value.
* Shallow Copy stores the references of objects to the original memory address.

**Removing rows from a dataframe**

In [ ]:
store_data.drop(1,axis=0)

        location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

In [ ]:
store_data

        location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1         Boston      M  Food&Beverages         3          75       5
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

* Notice that we used **`axis=0`** to drop a row from a data frame, while we were using **`axis=1`** for dropping a column from the data frame.
* Also, to make permanent changes to the data frame we will have to use `inplace=True` parameter.
* We also see that the index are not correct now as first row has been removed. So, we will have to reset the index of the data frame. Let's see how this can be done.

In [ ]:
# creating a new dataframe
store_data_new  = store_data.drop(1,axis=0)
store_data_new

        location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

In [ ]:
# resetting the index of data frame
store_data_new.reset_index()

   index       location gender            type  quantity  total_bill  rating
0      0        Chicago      M     Electronics         1         100       2
1      2        Seattle      F  Food&Beverages         4         125       3
2      3  San Francisco      M        Medicine         2          50       4
3      4         Austin      F          Beauty         1          80       4

* We see that the index of the data frame is now resetted but the index has become a column in the data frame. We do not need the index to become a column so we can simply set the parameter **`drop=True`** in reset_index() function.

In [ ]:
# setting inplace = True to make the changes permanent
store_data_new.reset_index(drop=True,inplace=True)
store_data_new

        location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1        Seattle      F  Food&Beverages         4         125       3
2  San Francisco      M        Medicine         2          50       4
3         Austin      F          Beauty         1          80       4

### 2.8 Pandas - Combining DataFrames

We will examine 3 methods for combining dataframes

1. concat
2. join
3. merge

In [ ]:
data_cust = pd.DataFrame({"customerID":['101','102','103','104'],
                        'category': ['Medium','Medium','High','Low'],
                        'first_visit': ['yes','no','yes','yes'],
                        'sales': [123,52,214,663]},index=[0,1,2,3])

data_cust_new = pd.DataFrame({"customerID":['101','103','104','105'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])

In [ ]:
data_cust

  customerID category first_visit  sales
0        101   Medium         yes    123
1        102   Medium          no     52
2        103     High         yes    214
3        104      Low         yes    663

In [ ]:
data_cust_new

  customerID  distance  sales
4        101        12    123
5        103         9    214
6        104        44    663
7        105        21    331

In [ ]:
pd.concat([data_cust,data_cust_new],axis=0)

  customerID category first_visit  sales  distance
0        101   Medium         yes    123       NaN
1        102   Medium          no     52       NaN
2        103     High         yes    214       NaN
3        104      Low         yes    663       NaN
4        101      NaN         NaN    123      12.0
5        103      NaN         NaN    214       9.0
6        104      NaN         NaN    663      44.0
7        105      NaN         NaN    331      21.0

In [ ]:
pd.concat([data_cust,data_cust_new],axis=1)

  customerID category first_visit  sales customerID  distance  sales
0        101   Medium         yes  123.0        NaN       NaN    NaN
1        102   Medium          no   52.0        NaN       NaN    NaN
2        103     High         yes  214.0        NaN       NaN    NaN
3        104      Low         yes  663.0        NaN       NaN    NaN
4        NaN      NaN         NaN    NaN        101      12.0  123.0
5        NaN      NaN         NaN    NaN        103       9.0  214.0
6        NaN      NaN         NaN    NaN        104      44.0  663.0
7        NaN      NaN         NaN    NaN        105      21.0  331.0

**Merge and Join**

* Merge combines dataframes using a column's values to identify common entries

* Join combines dataframes using the index to identify common entries

In [ ]:
pd.merge(data_cust,data_cust_new,how='outer',on='customerID') # outer merge is union of on

  customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0      12.0    123.0
1        102   Medium          no     52.0       NaN      NaN
2        103     High         yes    214.0       9.0    214.0
3        104      Low         yes    663.0      44.0    663.0
4        105      NaN         NaN      NaN      21.0    331.0

In [ ]:
pd.merge(data_cust,data_cust_new,how='inner',on='customerID') # inner merge is intersection of on

  customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes      123        12      123
1        103     High         yes      214         9      214
2        104      Low         yes      663        44      663

In [ ]:
pd.merge(data_cust,data_cust_new,how='right',on='customerID')

  customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0        12      123
1        103     High         yes    214.0         9      214
2        104      Low         yes    663.0        44      663
3        105      NaN         NaN      NaN        21      331

In [ ]:
data_quarters = pd.DataFrame({'Q1': [101,102,103],
                              'Q2': [201,202,203]},
                               index=['I0','I1','I2'])

data_quarters_new = pd.DataFrame({'Q3': [301,302,303],
                                  'Q4': [401,402,403]},
                               index=['I0','I2','I3'])

In [ ]:
data_quarters

     Q1   Q2
I0  101  201
I1  102  202
I2  103  203

In [ ]:
data_quarters_new

     Q3   Q4
I0  301  401
I2  302  402
I3  303  403

* `join` behaves just like merge,  except instead of using the values of one of the columns to combine data frames, it uses the index labels

In [ ]:
data_quarters.join(data_quarters_new,how='right') # outer, inner, left, and right work the same as merge

       Q1     Q2   Q3   Q4
I0  101.0  201.0  301  401
I2  103.0  203.0  302  402
I3    NaN    NaN  303  403

### 2.9 Pandas - Saving and Loading DataFrames

**Note**

In real-life scenario, we deal with much larger datasets that have thousands of rows and multiple columns. It will not be feasible for us to create datasets using multiple lists, especially if the number of columns and rows increases.

So, it is clear we need a more efficient way of handling the data simultaneously at the columns and row levels. In Python, we can import dataset from our local system, from links, or from databases and work on them directly instead of creating our own dataset.

**Loading a CSV file in Python**

**For Jupyter Notebook**
* When the data file and jupyter notebook are in the same folder.

In [4]:
# Using pd.read_csv() function will work without any path if the notebook and dataset are in the folder

# data = pd.read_csv('StockData.csv')

**For Google Colab with Google Drive**

First, we have to give google colab access to our google drive:

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Once we have access we can load files from google drive using read_csv() function.

In [6]:
path="/content/drive/MyDrive/Python Course/StockData.csv"
data=pd.read_csv(path)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Python Course/StockData.csv'

In [ ]:
# head() function helps us to see the first 5 rows of the data
data.head()

**Loading an excel file in Python**

In [ ]:
path_excel="/content/drive/MyDrive/Python Course/StockData.xlsx"
data_excel = pd.read_excel(path_excel)

In [ ]:
data_excel.head()

**Saving a dataset in Python**

**Saving the dataset as a csv file**

To save a dataset as .csv file the syntax used is -

**data.to_csv('name of the file.csv', index=False)**

In [ ]:
data.to_csv('/content/drive/MyDrive/Python Course/Saved_StockData.csv',index=False)

* In jupyter notebook, the dataset will be saved in the folder where the jupyter notebook is located.
* We can also save the dataset to a desired folder by providing the path/location of the folder.

**Saving the dataset as an excel spreadsheet**

To save a dataset as .xlsx file the syntax used is -

**data.to_excel('name of the file.xlsx',index=False)**

In [ ]:
data.to_excel('/content/drive/MyDrive/Python Course/Saved_StockData.xlsx',index=False)

### 2.10 Pandas - Functions

**head() - to check the first 5 rows of the dataset**

In [ ]:
data.head()

NameError: ignored

**tail() - to check the last 5 rows of the dataset**

In [ ]:
data.tail()

**shape - to check the number of rows and columns in the dataset**

In [ ]:
data.shape

* The dataset has 5036 rows and 3 columns.

**info() - to check the data type of the columns**

In [ ]:
data.info()

* The price column is numeric in nature while the stock and date columns are of object types.

**min() - to check the minimum value of a numeric column**

In [ ]:
data['price'].min()

**max() - to check the maximum value of a numeric column**

In [ ]:
data['price'].max()

**unique() - to check the number of unique values that are present in a column**

In [ ]:
data['stock'].unique()

**value_counts() - to check the number of values that each unique quantity has in a column**

In [ ]:
data['stock'].value_counts()

**value_counts(normalize=True) - using the `normalize` parameter and initializing it to True will return the relative frequencies of the unique values.**

In [13]:
data['books'].value_counts(normalize=True)

NameError: name 'data' is not defined

**Statistical Functions**

**mean() - to check the mean (average) value of the column**

In [ ]:
data['price'].mean()

**median() - to check the median value of the column**

In [ ]:
data['price'].median()

**mode() - to check the mode value of the column**

In [ ]:
data['stock'].mode()

**To access a particular mode when the dataset has more than 1 mode**

In [ ]:
#to access the first mode
data['price'].mode()[0]

**Group By function**
* Pandas dataframe.groupby() function is used to split the data into groups based on some criteria.

In [ ]:
data.groupby(['stock'])['price'].mean()

* Here the groupby function is used to split the data into the 4 stocks that are present in the dataset and then the mean price of each of the 4 stock is calculated.

In [ ]:
# similarly we can get the median price of each stock
data.groupby(['stock'])['price'].median()

* Here the groupby function is used to split the data into the 4 stocks that are present in the dataset and then the median price of each of the 4 stock is calculated.

**Let's create a function to increase the price of the stock by 10%**

In [ ]:
def profit(s):
    return s + s*0.10 # increase of 10%

**The Pandas apply() function lets you to manipulate columns and rows in a DataFrame.**

In [ ]:
data['price'].apply(profit)

* We can now add this updated values in the dataset.

In [ ]:
data['new_price'] =data['price'].apply(profit)
data.head()

**Pandas sort_values() function sorts a data frame in ascending or descending order of passed column.**

In [ ]:
data.sort_values(by='new_price',ascending=False) # by default ascending is set to True

### 2.11 Pandas - Date-time Functions

In [ ]:
# reading the StockData
path="/content/drive/MyDrive/Python Course/StockData.csv"
data=pd.read_csv(path)

In [ ]:
# checking the first 5 rows of the dataset
data.head()

In [ ]:
# checking the data type of columns in the dataset
data.info()

* We observe that the date column is of object type whereas it should be of date time data type.

In [ ]:
# converting the date column to datetime format
data['date']  = pd.to_datetime(data['date'],dayfirst=True)

In [ ]:
data.info()

* We observe that the date column has been converted to datetime format

In [ ]:
data.head()

**The column 'date' is now in datetime format. Now we can change the format of the date to any other format**

In [ ]:
data['date'].dt.strftime('%m/%d/%Y')

In [ ]:
data['date'].dt.strftime('%m-%d-%y')

**Extracting year from the date column**

In [ ]:
data['date'].dt.year

Creating a new column and adding the extracted year values into the dataframe.

In [ ]:
data['year'] = data['date'].dt.year

**Extracting month from the date column**

In [ ]:
data['date'].dt.month

Creating a new column and adding the extracted month values into the dataframe.

In [ ]:
data['month'] = data['date'].dt.month

**Extracting day from the date column**

In [ ]:
data['date'].dt.day

Creating a new column and adding the extracted day values into the dataframe.

In [ ]:
data['day'] = data['date'].dt.day

In [ ]:
data.head()

* We can see that year, month, and day columns have been added in the dataset.

In [ ]:
# The datetime format is convenient for many tasks!
data['date'][1]-data['date'][0]

# Test Practice

In [9]:
books = pd.read_csv('/content/drive/MyDrive/Class/Week 2/books.csv')

In [10]:
books.shape

(5000, 10)

In [11]:
books.select_dtypes(include=['object'])

,title,author,language_code,publisher
0,The Hunchback of Notre-Dame,Victor Hugo,en-US,Modern Library
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,en-GB,Clarkson Potter
2,Breach of Promise,James Scott Bell,eng,Zondervan
3,Brief Interviews with Hideous Men,David Foster Wallace,eng,Abacus
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,en-US,Berkley Hardcover
...,...,...,...,...
4995,The Complete Works,Michel de Montaigne,eng,Everyman's Library
4996,Shipwreck (Island I),Gordon Korman,eng,Scholastic Audio Books
4997,Every Night Italian: Every Night Italian,Giuliano Hazan,eng,Scribner
4998,Go Down Moses,William Faulkner,eng,Vintage
4999,The Avignon Quintet: Monsieur Livia Constanc...,Lawrence Durrell,en-US,Faber & Faber

In [16]:
avg_rating_greater_than_4 = books[books['average_rating'] > 4]
num_books_with_avg_gt_4 = avg_rating_greater_than_4.shape[0]
avg_rating_greater_than_4

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006
5,The Hand of Chaos (The Death Gate Cycle #5),Margaret Weis,4.06,9780553563696,eng,446.0,16301,117,Spectra,1993
6,On Intelligence,Jeff Hawkins,4.12,9780805078534,eng,261.0,5347,396,St. Martin's Griffin,2005
11,Merlin's Tour of the Universe,Neil deGrasse Tyson,4.02,9780385488358,eng,318.0,305,27,Main Street Books,1997
...,...,...,...,...,...,...,...,...,...,...
4991,'Salem's Lot,Stephen King,4.02,9780965772419,eng,405.0,1039,130,Doubleday,1975
4992,A Mad People's History of Madness,Dale Peterson,4.33,9780822953319,eng,384.0,9,0,University of Pittsburgh Press,1982
4993,A Christmas Carol (Great Illustrated Classics),Malvina G. Vogel,4.36,9781596792371,eng,238.0,466,31,Abdo Publishing Company,2005
4995,The Complete Works,Michel de Montaigne,4.44,9781400040216,eng,1392.0,166,13,Everyman's Library,2003
4999,The Avignon Quintet: Monsieur Livia Constanc...,Lawrence Durrell,4.07,9780571225552,en-US,1376.0,287,23,Faber & Faber,2004

In [22]:
df = books

In [21]:
books.query("language_code == 'eng'").groupby(['language_code'])['average_rating'].mean()

language_code
eng    3.931143
Name: average_rating, dtype: float64

In [32]:
df.loc[[1,4],['language_code', 'num_pages', 'ratings_count']]

  language_code  num_pages  ratings_count
1         en-GB      288.0             48
4         en-US      368.0          59524

In [33]:
 books.query['num_pages'].mean()

TypeError: 'method' object is not subscriptable

In [39]:
books['num_pages'].median()

304.0

In [46]:
pub_authors = books[books['publisher'] == 'DAW'].groupby('author')['average_rating'].mean().reset_index()
authors_avg_gt_4 = pub_authors[pub_authors['average_rating'] > 4]['author']
print(authors_avg_gt_4)

4    Mercedes Lackey
6       Sharon Green
Name: author, dtype: object

In [65]:
books[(books['num_pages'] > 500) & (books['year'] > 2010)]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
2045,Billy Budd Sailor and Other Uncompleted Writi...,Herman Melville,3.11,9780810111141,eng,1016.0,0,0,Northwestern Univ Press,2017
2775,Rick Steves' Europe Through the Back Door,Rick Steves,4.24,9781566918084,eng,808.0,3569,70,Avalon Travel,2017
3075,The Iliad,Homer,3.86,9781904633389,eng,542.0,64,8,Collector's Library,2011
3157,George Washington's Sacred Fire,Peter A. Lillback,4.18,9780978605261,eng,1200.0,694,63,Providence Forum Press,2011
3546,The Will to Power,Friedrich Nietzsche,4.05,9780394704371,eng,575.0,7931,132,Vintage Books,2011

In [61]:
books[books['author'] == "Agatha Christie"]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
809,One Two Buckle My Shoe (Hercule Poirot #23),Agatha Christie,3.76,9781572703858,eng,NaN,14388,411,HarperCollins Publishers,2004
850,A Murder Is Announced (Miss Marple #5),Agatha Christie,3.98,9781579126292,eng,288.0,33195,1220,Black Dog & Leventhal Publishers,2006
865,The Listerdale Mystery And Eleven Other Stories,Agatha Christie,3.56,9781572704978,eng,NaN,1824,89,AudioGO,2006
969,Death on the Nile (Hercule Poirot #17),Agatha Christie,4.10,9781579126896,eng,351.0,674,91,Black Dog & Leventhal Publishers,2007
1021,Cards on the Table (Hercule Poirot #15),Agatha Christie,3.92,9780425205952,eng,324.0,25236,1046,Berkley,2005
1396,And Then There Were None,Agatha Christie,4.26,9780312330873,eng,264.0,625767,18785,St. Martin's Press,2004
1433,Hallowe'en Party (Hercule Poirot #39),Agatha Christie,3.66,9780007120680,eng,336.0,20656,1246,Harper,2001
1448,Hickory Dickory Dock (Hercule Poirot #32),Agatha Christie,3.75,9781572705647,eng,196.0,13515,368,AudioGO,2006
1696,The Unexpected Guest: A Play In Two Acts,Agatha Christie,3.83,9780573014673,eng,100.0,2813,167,Samuel French Ltd,2010
2041,The Labours of Hercules (Hercule Poirot #27),Agatha Christie,3.78,9781572704572,eng,9.0,11167,297,AudioGO,2005
2322,Sleeping Murder (Miss Marple #13),Agatha Christie,3.95,9780002317856,eng,242.0,19657,884,Dodd Mead; 1st edition (September 1976),2003
2598,Evil Under the Sun (Hercule Poirot #24),Agatha Christie,3.97,9781579126285,eng,220.0,36334,975,Black Dog & Leventhal Publishers,2006
2966,Murder on the Orient Express (Hercule Poirot ...,Agatha Christie,4.17,9780425200452,eng,322.0,145660,5711,Berkley,2004
3053,A Caribbean Mystery (Miss Marple #10),Agatha Christie,3.80,9780451199928,eng,224.0,18590,770,Signet,2000
3190,Agatha Christie: An Autobiography,Agatha Christie,4.27,9780006353287,eng,560.0,4296,310,HarperCollins,2001
3819,Miss Marple Omnibus Vol. 3 (Murder at the Vica...,Agatha Christie,4.32,9780006499619,eng,688.0,138,5,Harper Collins,1997
3943,Five Complete Miss Marple Novels: The Mirror C...,Agatha Christie,4.39,9780517035801,eng,650.0,116,6,Avenel Books,1990
4402,After the Funeral,Agatha Christie,3.87,9780002310192,eng,251.0,47,4,HarperCollins,2001
4468,The A.B.C. Murders (Hercule Poirot #13),Agatha Christie,4.01,9781579126247,eng,252.0,69806,2470,Black Dog & Leventhal Publishers,2006
4728,They Do It With Mirrors,Agatha Christie,3.76,9781559277587,eng,7.0,2,0,MacMillan Audio,2002
4894,Nemesis (Miss Marple #12),Agatha Christie,3.85,9780451200181,eng,224.0,18896,771,Signet,2000

In [68]:
books[(books['year'] > 2000) & (books['language_code'] == 'spa')]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
21,Los funerales de la Mamá Grande,Gabriel García Márquez,3.78,9780307350329,spa,160.0,4694,133,Plaza y Janes,2006
53,La Emperatriz tras el velo (Trilogía Taj Mahal...,Indu Sundaresan,4.04,9788425337604,spa,382.0,2,1,Grijalbo Mondadori Sa,2003
69,La casa de los espíritus,Isabel Allende,4.23,9780060951306,spa,454.0,608,38,HarperCollins Espanol,2001
93,Ya Sé Que Te Quiero,Billy Crystal,4.19,9780060845988,spa,40.0,0,0,Rayo,2006
107,Secretos De Familia,Julia Glass,3.57,9788496525030,spa,528.0,0,1,Puzzle-Roca,2006
...,...,...,...,...,...,...,...,...,...,...
4804,Muerte Blanca,Clive Cussler,3.91,9780307343260,spa,421.0,2,0,Debolsillo,2005
4832,Entrevista con el vampiro (Crónicas vampíricas...,Anne Rice,3.99,9788466616201,spa,463.0,1307,93,Ediciones B,2005
4890,Isabel: Princesa De Castilla España 1466,Carolyn Meyer,3.71,9788478886746,spa,184.0,8,0,Salamandra,2001
4907,Ve perro ¡Ve!,P.D. Eastman,4.09,9780375823619,spa,24.0,33,2,Random House Para Ninos,2003
4951,El librero de Kabul,Åsne Seierstad,3.76,9789706519245,spa,285.0,112,18,Grupo Océano,2004

In [69]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [71]:
demo_array = np.array([13,35,74,48,45,76,23,65,84,52])

In [72]:
demo_array[0:7] = 5
demo_array

array([ 5,  5,  5,  5,  5,  5,  5, 65, 84, 52])

In [73]:
demo_array = np.arange(0,10)
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [74]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5